version: '3.9'
services:
  frontend:
    image: 'lizdockerhub/lizreactapp'
    ports:
      - '8002:80'
  backend:
    image: 'lizdockerhub/dotnetapp'
    ports:
      - '8001:80'
  db:
    image: 'mysql'
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
     
