pipeline{
     environment{
        IMG_TAG="${sh(script: 'echo \$GIT_COMMIT | cut -c -7 | tr -d \'[:space:]\' ', returnStdout: true ) }.$BUILD_NUMBER"
        APP_NAME="bankingAPI"
    }
    agent {
        dockerfile {
            dir 'jenkins/'
        }
    }

    stages{

        stage('Unit test'){
            steps{
                sh 'ls -la'
                sh 'pwd'
                sh 'dotnet test BankingAPI/BankingAPIs.Test/BankingAPIs.Test.csproj'
            }
        }
    
        stage('Build image'){
            steps{
             
                script {
                    bankingAPIImage = docker.build("$APP_NAME:$IMG_TAG", "-f bankingAPI/Dockerfile .")
                }
            
            }
        }
        stage('Push image'){
          when {
              anyOf {
                 branch 'main'
                 branch 'dev'
              }
           }
            steps{
                script{
                    sh "docker login -u ${env.username} -p ${env.password}"
                    sh "docker push lizdockerhub/dotnetapp"
                }
                
            }
        }
        stage('Logout'){
            steps{
                script{
                    sh "docker logout"
                }
                
            }
        }
    }   
    
}
